-- insert into product(id, name, quantity) values ('Chair', 50)
-- insert into product(id, name, quantity) values ('Table', 15)
-- insert into product(id, name, quantity) values ('Monitor', 150)
-- insert into product(id, name, quantity) values ('Keyboard', 300)